name: CI/CD Workflow

# Eventos que activan el workflow
on:
  push:
    branches:
      - main   # Ejecuta el workflow al hacer push en la rama principal
  pull_request:
    branches:
      - main   # Ejecuta el workflow en cada pull request a la rama principal

# Definición de trabajos (jobs)
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest # Usa el sistema operativo Ubuntu más reciente
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Descarga el código fuente

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Configura la versión de Node.js

      - name: Install dependencies
        run: npm install # Instala las dependencias del proyecto

      - name: Run tests
        run: npm test # Ejecuta las pruebas

  build:
    name: Build Application
    needs: test # Este trabajo se ejecuta después de que el trabajo de pruebas pase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build # Construye la aplicación

  deploy:
    name: Deploy to AWS S3
    needs: build # Este trabajo se ejecuta después de que el trabajo de construcción pase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync files to S3
        run: |
          aws s3 sync ./build s3://your-s3-bucket-name --delete
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

  notify:
    name: Notify Deployment Status
    needs: deploy # Este trabajo se ejecuta después de que el despliegue pase
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON_EMOJI: ":rocket:"
        with:
          args: |
            Deployment to AWS S3 was successful for branch: ${{ github.ref_name }}.
